import "server-only";

import type { Prisma } from "@prisma/client";
import { NextResponse } from "next/server";
import { z } from "zod";

import { apiError, withErrorHandling } from "@/lib/api";
import { applicationRowSelect, serializeApplicationRow } from "@/lib/application-rows";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { requirePermission } from "@/lib/permissions";
import { applicationWhere } from "@/lib/scopes";

const createSchema = z.object({
  title: z.string().min(1, "Enter a filing title.").max(160),
  pharmacyId: z.string().uuid("Choose the pharmacy this filing belongs to."),
});

/** Upper bound on a page so a wide scope cannot pull the whole table at once. */
const MAX_LIMIT = 100;
const DEFAULT_LIMIT = 50;

const statusFilter = z
  .enum(["pending", "in_review", "reported", "rejected"])
  .optional();

/**
 * GET /api/applications
 *
 * Scoped from the session, never from a tenant id in the query string. A worker
 * sees their own pharmacy's filings, an association admin their association's,
 * and super admins and moderators everything — the same rule
 * `lib/scopes.ts` applies to every other listing.
 */
export const GET = withErrorHandling(async (request: Request) => {
  const actor = await requireUser();
  const params = new URL(request.url).searchParams;

  const search = params.get("q")?.trim() ?? "";
  const status = statusFilter.safeParse(params.get("status") ?? undefined);
  if (!status.success) {
    return apiError("invalid", "Unknown status filter.", 400);
  }

  // Clamp rather than trust: an unbounded `limit` is a cheap way to pull the
  // whole estate into one response, so `?limit=100000` degrades to the cap
  // instead of being honoured.
  const requested = Number(params.get("limit") ?? DEFAULT_LIMIT);
  const limit = Number.isFinite(requested)
    ? Math.min(Math.max(Math.trunc(requested), 1), MAX_LIMIT)
    : DEFAULT_LIMIT;

  const scoped = applicationWhere(actor);
  const filters: Prisma.ApplicationWhereInput[] = [scoped];
  if (status.data) filters.push({ status: status.data });
  if (search) {
    filters.push({
      OR: [
        { title: { contains: search, mode: "insensitive" } },
        { reference: { contains: search, mode: "insensitive" } },
        { pharmacy: { name: { contains: search, mode: "insensitive" } } },
        { association: { name: { contains: search, mode: "insensitive" } } },
        { submittedBy: { name: { contains: search, mode: "insensitive" } } },
      ],
    });
  }

  const applications = await prisma.application.findMany({
    where: { AND: filters },
    select: applicationRowSelect,
    // Newest first, with `reference` as the tiebreaker so two filings submitted
    // in the same millisecond (which the seeded data does) keep a stable order
    // across requests. Without it, pagination can repeat or skip a row.
    orderBy: [{ submittedAt: "desc" }, { reference: "desc" }],
    take: limit,
  });

  return NextResponse.json({
    ok: true,
    applications: applications.map(serializeApplicationRow),
  });
});

/**
 * POST /api/applications
 *
 * Creates the filing, then the browser uploads each file against the returned
 * id (`POST /api/uploads` → presigned PUT → `/complete`). Files are *not* taken
 * in this request: the completion step is what re-derives size, checksum and
 * schema validation from the stored bytes, so accepting file metadata here would
 * mean storing claims the server has not checked.
 *
 * The `reference` is generated by `application_reference_seq` — see
 * `prisma/migrations/20260930_application_reference_seq`. The client never sends
 * one, so two concurrent submissions cannot collide on the unique index.
 */
export const POST = withErrorHandling(async (request: Request) => {
  const actor = await requireUser();

  const parsed = createSchema.safeParse(await request.json().catch(() => null));
  if (!parsed.success) {
    return apiError("invalid", parsed.error.issues[0]?.message ?? "Invalid request.", 400);
  }

  // Resolve the pharmacy *before* authorizing: `createApplication` for an
  // association admin needs `pharmacyAssociationId`, and that is only knowable
  // from the pharmacy row. Authorizing first would have nothing to check
  // against, which is exactly the gap that let a body-supplied associationId
  // become an IDOR in the first place.
  const pharmacy = await prisma.pharmacy.findUnique({
    where: { id: parsed.data.pharmacyId },
    select: { id: true, associationId: true, status: true },
  });
  if (!pharmacy) {
    return apiError("invalid", "That pharmacy does not exist.", 400);
  }
  if (pharmacy.status !== "active") {
    return apiError("invalid", "That pharmacy is not active.", 400);
  }

  try {
    requirePermission(actor, "createApplication", {
      pharmacyId: pharmacy.id,
      pharmacyAssociationId: pharmacy.associationId,
    });
  } catch {
    return apiError("forbidden", "You cannot file for that pharmacy.", 403);
  }

  const association = await prisma.pharmacyAssociation.findUnique({
    where: { id: pharmacy.associationId },
    select: { status: true },
  });
  if (!association || association.status !== "active") {
    return apiError("invalid", "That association is not active.", 400);
  }

  const created = await prisma.$transaction(async (tx) => {
    const application = await tx.application.create({
      data: {
        title: parsed.data.title.trim(),
        pharmacyId: pharmacy.id,
        // Denormalised on purpose: `lib/upload-access.ts` authorizes every file
        // read from these two columns without a join, and they are only ever
        // written here, from the pharmacy's own association.
        associationId: pharmacy.associationId,
        submittedById: actor.id,
      },
      select: { id: true },
    });

    // The opening `pending` event is written in the same transaction as the
    // filing. A filing with no history is indistinguishable from a filing whose
    // audit trail was lost, and the event table exists to make that distinction
    // impossible.
    await tx.statusEvent.create({
      data: {
        applicationId: application.id,
        fromStatus: null,
        to: "pending",
        changedById: actor.id,
        note: "Filing received through the intake form.",
      },
    });

    return application;
  });

  const row = await prisma.application.findUniqueOrThrow({
    where: { id: created.id },
    select: applicationRowSelect,
  });

  // Spread flat, like `GET /api/applications/[id]`. Nesting the row under a
  // second `application` key would give the same field two meanings across
  // routes (`body.application` being the filing on one route and the whole row
  // on another), and the client mapper would need a per-route special case.
  return NextResponse.json({ ok: true, ...serializeApplicationRow(row) }, { status: 201 });
});
