import { CtaBand, PageHeader, SectionHead, Stat } from "@/components/marketing";
import { ROLE_MATRIX } from "@/lib/marketing-content";

export const metadata = {
  title: "Documentation — SiroQ",
  description:
    "SiroQ documentation: the request contract and error shapes, the authorization specification, the dispensing file manifest, and the filing state machine.",
};

/**
 * Reference documentation.
 *
 * This mirrors the implementation rather than an aspiration: the error codes,
 * the HTTP semantics, the manifest columns and the role matrix are transcribed
 * from the modules that enforce them. Where a behaviour is deliberately
 * documented as absent, it is called out in a "Not implemented" block — the
 * page is a specification, and a specification with holes left implicit is
 * worse than one that names them.
 */

const ERRORS = [
  ["400", "invalid", "The request was malformed or failed schema validation. The body names the offending field where one can be identified."],
  ["401", "unauthorized", "No session, or the session is expired. Sessions are opaque and server-side; there is no token to inspect client-side."],
  ["403", "forbidden", "The session is valid but the role lacks the action, or the resource is outside the caller's scope. The two are indistinguishable to the caller by design."],
  ["404", "not_found", "No such record within the caller's scope. A record that exists in another tenant is reported as not found, not as forbidden."],
  ["409", "conflict", "The change would contradict current state — for example re-attaching a report to a filing that already has a delivered one."],
  ["500", "server_error", "An unhandled failure. The detail is logged server-side and never returned, so responses cannot fingerprint the deployment."],
];

const ENDPOINTS = [
  ["POST", "/api/auth/signup", "Any", "Creates a pending request. Produces an invited account with no tenant and no usable permissions."],
  ["POST", "/api/auth/login", "Any", "Exchanges credentials for an opaque, hashed, httpOnly session cookie."],
  ["POST", "/api/auth/logout", "Session", "Revokes the current session server-side rather than clearing the cookie alone."],
  ["POST", "/api/uploads", "Session", "Issues a presigned upload URL and a staging key bound to the caller."],
  ["POST", "/api/uploads/[id]/complete", "Session", "Hashes and inspects the stored bytes, then binds the file to a filing."],
  ["GET", "/api/applications", "Session", "List filings, filtered and scoped from the session. No scope is accepted as a parameter."],
  ["POST", "/api/applications", "Session", "Create a filing. The reference is generated by a database sequence."],
  ["POST", "/api/applications/[id]/status", "Session", "Move a filing between states. Writes the status event in the same transaction."],
  ["POST", "/api/applications/[id]/report", "Super admin", "Attach a report. Refused when a delivered report is already present."],
  ["GET", "/api/applications/[id]/raw", "Super admin", "Streams the stored document through an authorised endpoint. Never a public URL."],
];

export default function DocsPage() {
  return (
    <>
      <PageHeader
        eyebrow="Documentation"
        title="The contract, the boundary, and the manifest."
        lede="Three references that answer most integration and security-review questions: what the API accepts and returns, who may do what, and what a dispensing file has to contain."
      >
        <div className="grid gap-3 sm:grid-cols-4">
          <Stat label="Error codes" value="6" />
          <Stat label="Access roles" value="4" />
          <Stat label="Manifest columns" value="2" />
          <Stat label="Filing states" value="4" />
        </div>
      </PageHeader>

      <nav aria-label="Sections" className="section flex flex-wrap gap-2 pb-12">
        {[
          ["#api", "API"],
          ["#errors", "Errors"],
          ["#authorization", "Authorization"],
          ["#manifest", "File manifest"],
          ["#states", "States"],
          ["#not-implemented", "Not implemented"],
        ].map(([href, label]) => (
          <a
            key={href}
            href={href}
            className="rounded-full border border-hairline px-3 py-1.5 text-[12px] text-muted transition-colors hover:border-accent hover:text-ink"
          >
            {label}
          </a>
        ))}
      </nav>

      {/* ------------------------------------------------------------------ api */}
      <section id="api" className="scroll-mt-20 border-t border-hairline">
        <div className="section py-16">
          <SectionHead
            eyebrow="API"
            title="Request contract"
            lede="Everything is JSON except the raw document stream. Sessions travel in an httpOnly cookie and are never read by client JavaScript."
          />

          <div className="mt-10 overflow-hidden rounded-card border border-hairline">
            <div className="overflow-x-auto">
              <table className="ruled-table w-full min-w-[46rem] text-left text-[13px]">
                <caption className="sr-only">HTTP methods and access requirements</caption>
                <thead>
                  <tr>
                    <th scope="col" className="px-4 py-3">Method</th>
                    <th scope="col" className="px-4 py-3">Path</th>
                    <th scope="col" className="px-4 py-3">Requires</th>
                    <th scope="col" className="px-4 py-3">Behaviour</th>
                  </tr>
                </thead>
                <tbody>
                  {ENDPOINTS.map(([method, path, requires, behaviour]) => (
                    <tr key={path}>
                      <td className="px-4 py-3 font-mono text-[12px] text-accent-strong">{method}</td>
                      <td className="px-4 py-3 font-mono text-[12px] text-ink">{path}</td>
                      <td className="px-4 py-3 text-[12px] text-muted">{requires}</td>
                      <td className="px-4 py-3 text-[12px] text-muted">{behaviour}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          <div className="mt-8 prose-doc max-w-3xl">
            <h3>Uploads are staged, then bound</h3>
            <p>
              Bytes are uploaded directly to storage with a presigned URL and staged unattached.
              The filing binding happens in the completion call, after the server has hashed and
              inspected the stored bytes. This ordering is deliberate: an interrupted transfer
              leaves a staged object and no filing, rather than a filing that exists but is empty.
            </p>
          </div>
        </div>
      </section>

      {/* --------------------------------------------------------------- errors */}
      <section id="errors" className="scroll-mt-20 border-t border-hairline bg-paper-raised">
        <div className="section py-16">
          <SectionHead
            eyebrow="Errors"
            title="One shape, always"
            lede="Every API route returns the same error body, so a client needs one parser rather than one per endpoint."
          />
          <div className="mt-8 overflow-x-auto rounded-card border border-hairline bg-paper-raised">
            <pre className="overflow-x-auto p-5 font-mono text-[12px] leading-relaxed text-ink">
{`{
  "error": {
    "code": "forbidden",
    "message": "You do not have access to this filing."
  }
}`}
            </pre>
          </div>

          <div className="mt-8 overflow-hidden rounded-card border border-hairline bg-paper-raised">
            <div className="overflow-x-auto">
              <table className="ruled-table w-full min-w-[42rem] text-left text-[13px]">
                <caption className="sr-only">HTTP status codes and their meanings</caption>
                <thead>
                  <tr>
                    <th scope="col" className="px-4 py-3">Status</th>
                    <th scope="col" className="px-4 py-3">Code</th>
                    <th scope="col" className="px-4 py-3">Meaning</th>
                  </tr>
                </thead>
                <tbody>
                  {ERRORS.map(([status, code, meaning]) => (
                    <tr key={code}>
                      <td className="px-4 py-3 font-mono text-[12px] text-ink">{status}</td>
                      <td className="px-4 py-3 font-mono text-[12px] text-accent-strong">{code}</td>
                      <td className="px-4 py-3 text-[12px] text-muted">{meaning}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          <div className="mt-8 prose-doc max-w-3xl">
            <h3>Why 404 rather than 403 for another tenant</h3>
            <p>
              A filing that exists in a different tenant is reported as <code>not_found</code>. A
              <code> forbidden</code> response would confirm the identifier is real, which turns the
              endpoint into a probe for validating ids belonging to other customers. The distinction
              is deliberate and it is the reason the raw-document route behaves the same way.
            </p>
          </div>
        </div>
      </section>

      {/* -------------------------------------------------------- authorization */}
      <section id="authorization" className="scroll-mt-20 border-t border-hairline">
        <div className="section py-16">
          <SectionHead
            eyebrow="Authorization"
            title="The specification"
            lede="One module holds every permission decision, and every route defers to it. This is that module's public contract."
          />

          <div className="mt-10 prose-doc max-w-3xl">
            <h3>Rules that hold everywhere</h3>
            <ol>
              <li>Scope is derived from the session on every request. No route accepts an association, pharmacy or role as a client-supplied parameter.</li>
              <li>A non-active user is denied every action, regardless of what their session claims.</li>
              <li>A record outside the caller&apos;s scope is reported as not found, and never as forbidden.</li>
              <li>Role checks answer whether the action is permitted; a separate ownership check answers whether it is permitted on this record.</li>
              <li>Every mutation re-checks. A list endpoint being scoped is not a substitute for the detail route checking too.</li>
            </ol>
          </div>

          <div className="mt-12 grid gap-5 lg:grid-cols-2">
            {ROLE_MATRIX.map((entry) => (
              <div key={entry.role} className="card p-7">
                <h3 className="font-mono text-[12px] tracking-[0.06em] text-ink">{entry.role}</h3>
                <p className="mt-1.5 text-[12px] text-muted">{entry.audience}</p>
                <p className="req-field-label mt-6">Permitted</p>
                <ul className="mt-2 space-y-1.5 text-[13px] text-muted">
                  {entry.can.map((item) => (
                    <li key={item} className="flex gap-2">
                      <span aria-hidden="true" className="text-accent">✓</span>
                      {item}
                    </li>
                  ))}
                </ul>
                <p className="req-field-label mt-6">Refused</p>
                <ul className="mt-2 space-y-1.5 text-[13px] text-muted">
                  {entry.cannot.map((item) => (
                    <li key={item} className="flex gap-2">
                      <span aria-hidden="true" className="text-status-rejected">✕</span>
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          <div className="mt-10 prose-doc max-w-3xl">
            <h3>Session shape</h3>
            <p>
              Sessions are opaque: the cookie carries a random identifier, and the record behind it
              is stored hashed. Nothing about the user is encoded in the cookie, so there is no
              token to decode, tamper with or forge. Revocation is immediate — deactivating a user
              ends their sessions rather than waiting for a cookie to expire.
            </p>
          </div>
        </div>
      </section>

      {/* ------------------------------------------------------------- manifest */}
      <section id="manifest" className="scroll-mt-20 border-t border-hairline bg-paper-raised">
        <div className="section py-16">
          <SectionHead
            eyebrow="Intake"
            title="What a dispensing file has to contain"
            lede="Checked server-side against the stored bytes. Structural defects are refused with the missing names; ragged rows warn."
          />

          <div className="mt-10 overflow-hidden rounded-card border border-hairline bg-paper-raised">
            <div className="overflow-x-auto">
              <table className="ruled-table w-full min-w-[36rem] text-left text-[13px]">
                <caption className="sr-only">Required manifest columns</caption>
                <thead>
                  <tr>
                    <th scope="col" className="px-4 py-3">Column</th>
                    <th scope="col" className="px-4 py-3">Requirement</th>
                    <th scope="col" className="px-4 py-3">If absent</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className="px-4 py-3 font-mono text-[12px] text-ink">NDC code</td>
                    <td className="px-4 py-3 text-[12px] text-muted">Must appear in the header row. Matched case-insensitively.</td>
                    <td className="px-4 py-3 text-[12px] text-muted">File refused, missing column named</td>
                  </tr>
                  <tr>
                    <td className="px-4 py-3 font-mono text-[12px] text-ink">Batch number</td>
                    <td className="px-4 py-3 text-[12px] text-muted">Must appear in the header row. Matched case-insensitively.</td>
                    <td className="px-4 py-3 text-[12px] text-muted">File refused, missing column named</td>
                  </tr>
                  <tr>
                    <td className="px-4 py-3 font-mono text-[12px] text-ink">Any further column</td>
                    <td className="px-4 py-3 text-[12px] text-muted">Detected and recorded. Extra columns are not a defect.</td>
                    <td className="px-4 py-3 text-[12px] text-muted">n/a</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <div className="mt-10 prose-doc max-w-3xl">
            <h3>Verdicts</h3>
            <ul>
              <li><strong>valid</strong> — every row matched the header width and the manifest is satisfied.</li>
              <li><strong>warning</strong> — accepted with a named defect, currently ragged rows. The count is reported.</li>
              <li><strong>invalid</strong> — refused. Either the manifest is unsatisfied, the header is empty, the CSV has no rows, or the file is not really the format it claims.</li>
            </ul>
            <h3>CSV specifics</h3>
            <p>
              The splitter implements RFC 4180: quoted fields, embedded commas and escaped quotes
              (<code>{String.fromCharCode(34, 34)}</code>) are handled, so a quoted value containing a comma does not inflate
              the column count. A UTF-8 byte-order mark is stripped before the header is read.
            </p>
            <h3>Workbook specifics</h3>
            <p>
              An <code>.xlsx</code> is validated as a ZIP container, which catches a renamed CSV.
              Sheet contents are not parsed at intake, so row and column counts are not reported for
              workbooks until they are parsed on demand.
            </p>
          </div>
        </div>
      </section>

      {/* --------------------------------------------------------------- states */}
      <section id="states" className="scroll-mt-20 border-t border-hairline">
        <div className="section py-16">
          <SectionHead
            eyebrow="Lifecycle"
            title="Filing states and the events they emit"
            lede="Four states. Every transition writes a status event inside the transaction that performs it."
          />
          <div className="mt-10 grid gap-5 md:grid-cols-2">
            {[
              ["pending", "stamp-pending", "Submitted and awaiting review. No assessment has taken place."],
              ["in_review", "stamp-in_review", "An administrator has taken it up. Intake verdict and findings are attached."],
              ["reported", "stamp-reported", "A report is attached. The delivered result for this filing."],
              ["rejected", "stamp-rejected", "Returned with a reason. History is retained and the filing can be corrected and resubmitted."],
            ].map(([state, tone, meaning]) => (
              <div key={state} className="card p-6">
                <span className={`stamp ${tone}`}>{state}</span>
                <p className="mt-4 text-[13px] leading-relaxed text-muted">{meaning}</p>
              </div>
            ))}
          </div>
          <div className="mt-8 prose-doc max-w-3xl">
            <p>
              A status event records the actor, the previous state, the new state and the time. It is
              written in the same transaction as the transition, so a transition that fails leaves no
              gap in the history. A delivered report is not overwritable — correcting one requires
              reopening the filing, and the reopen is itself an event.
            </p>
          </div>
        </div>
      </section>

      {/* ----------------------------------------------------- not implemented */}
      <section id="not-implemented" className="scroll-mt-20 border-t border-hairline bg-paper-raised">
        <div className="section py-16">
          <SectionHead
            eyebrow="Not implemented"
            title="The gaps, in the documentation itself"
            lede="A spec that hides its holes is marketing. These are the ones we know about."
          />
          <div className="mt-10 overflow-hidden rounded-card border border-hairline bg-paper-raised">
            <ul className="divide-y divide-hairline">
              {[
                ["Per-cell content analysis", "Date ranges, quantity types and NDC format are not validated. Intake checks structure and manifest only."],
                ["Workbook sheet parsing", "XLSX files are validated as containers at intake; sheet contents are not read."],
                ["Rate limiting", "The contact form has an in-process counter that blunts casual spam. It resets on deploy and does not apply across instances."],
                ["Bulk import", "There is no importer for backfilling existing filings. Onboarding handles it manually."],
                ["Encryption at the application layer", "No envelope encryption or customer-managed keys. Encryption is at the transport and storage-provider layer."],
                ["Single sign-on", "Authentication is password plus session cookie. No SAML or OIDC provider."],
                ["Self-hosting", "Runs on ordinary Node and PostgreSQL, but no supported self-hosted distribution exists."],
              ].map(([item, detail]) => (
                <li key={item} className="flex flex-wrap gap-x-4 gap-y-1 px-6 py-4">
                  <span className="text-[13px] font-medium text-ink">{item}</span>
                  <span className="text-[13px] text-muted">{detail}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      <CtaBand
        title="Need something documented that is not here?"
        body="Security reviews usually go deeper than a public page. Ask and we will answer with the module rather than the summary."
        primary={{ href: "/contact", label: "Request a security review" }}
        secondary={{ href: "/faq", label: "Read the FAQ" }}
      />
    </>
  );
}
