import Link from "next/link";
import { CtaBand, DisclosureList, PageHeader, SectionHead } from "@/components/marketing";

export const metadata = {
  title: "How it works — SiroQ",
  description:
    "The SiroQ filing lifecycle: submit, validate, review, report — including what happens when an upload fails, a file is rejected, or a report has to be corrected.",
};

const STEPS = [
  {
    n: "01",
    title: "Submit",
    actor: "Pharmacy worker or association admin",
    body: "A filing is created against one pharmacy for one period. Files are uploaded against it, and the reference — AP-2026-0142 and similar — is generated by a database sequence, not by the browser, so it is unique across the deployment and citable in correspondence.",
    detail: [
      "Bytes are staged first and the filing is created once the transfer completes, so an interrupted upload leaves no half-created filing behind.",
      "If the failure happens after the filing exists, the reference is shown on screen and the partial filing stays visible rather than being hidden from the queue.",
      "Multiple files can belong to one filing, because the review unit is the submission rather than the attachment.",
    ],
  },
  {
    n: "02",
    title: "Validate",
    actor: "Automatic, at intake",
    body: "Each file is inspected against the bytes that were stored, and returns valid, warning or invalid with the reason in words. SHA-256 is recorded over those same bytes.",
    detail: [
      "A CSV missing NDC code or Batch number in its header is refused, and the missing columns are named in the error. Header matching is case-insensitive.",
      "Ragged rows produce a warning naming how many rows were padded or truncated, rather than a rejection — and workbook containers are checked as ZIP archives so a renamed CSV is caught.",
      "Per-cell content analysis — date ranges, quantity types, NDC format — is not implemented yet. It is listed on the compliance page, and it is not implied anywhere else on this site.",
      "The stored document is served through an authorised endpoint, never a public URL.",
    ],
  },
  {
    n: "03",
    title: "Review",
    actor: "Association admin or super admin",
    body: "A filing moves pending → in review → reported, or → rejected with a reason. Each transition writes a status event recording the actor, the previous state and the new state.",
    detail: [
      "The event and the change are written in one transaction. A transition that fails leaves no gap in the history.",
      "A rejected filing keeps its history and carries the reason it was returned, so the pharmacy can fix and resubmit and the reviewer can see that they did.",
      "The timeline a reviewer sees is the stored history — there is no tidier parallel version kept for display.",
    ],
  },
  {
    n: "04",
    title: "Report",
    actor: "Super admin only",
    body: "The report is attached to the filing and becomes the delivered result. Structured results and the source document are stored separately, so the panel renders nested results without re-parsing the file.",
    detail: [
      "A delivered report cannot be replaced. Correcting one means reopening the filing, which records its own audit event.",
      "Re-attaching is refused while a final report is present, rather than silently overwriting the delivered document.",
      "The report records who produced it, its source and the engine version, if the analysis service is enabled.",
    ],
  },
];

const LIFECYCLE = [
  { state: "Pending", tone: "stamp-pending", meaning: "Submitted and awaiting review. Nothing has been assessed yet." },
  { state: "In review", tone: "stamp-in_review", meaning: "An administrator has picked it up. Findings are attached to the filing." },
  { state: "Reported", tone: "stamp-reported", meaning: "A report has been attached. This is the terminal state for a successful review." },
  { state: "Rejected", tone: "stamp-rejected", meaning: "Returned with a reason. The filing stays visible, with its history intact, so it can be corrected and resubmitted." },
];

export default function HowItWorksPage() {
  return (
    <>
      <PageHeader
        eyebrow="How it works"
        title="Four steps, one audit trail, and the failure states documented."
        lede="Most process descriptions stop at the happy path. The interesting behaviour — what happens when an upload dies halfway, or a report turns out to be wrong — is below."
      />

      {/* Status lifecycle: the reference table people actually look up. */}
      <section className="section pb-16">
        <div className="card overflow-hidden p-0">
          <div className="border-b border-hairline px-6 py-4">
            <p className="text-[13px] font-medium text-ink">Filing states</p>
          </div>
          <ul className="divide-y divide-hairline">
            {LIFECYCLE.map((state) => (
              <li key={state.state} className="flex flex-wrap items-baseline gap-x-4 gap-y-1 px-6 py-4">
                <span className={`stamp ${state.tone} shrink-0`}>{state.state}</span>
                <span className="text-[13px] leading-relaxed text-muted">{state.meaning}</span>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {STEPS.map((step, index) => (
        <section
          key={step.n}
          className={`border-t border-hairline ${index % 2 === 1 ? "bg-paper-raised" : ""}`}
        >
          <div className="section py-16">
            <div className="grid gap-10 lg:grid-cols-[minmax(0,0.85fr)_minmax(0,1.4fr)]">
              <div>
                <p className="font-mono text-[11px] tracking-[0.12em] text-accent">{step.n}</p>
                <h2 className="mt-3 text-2xl font-semibold tracking-tight text-ink">{step.title}</h2>
                <div className="signature-rule mt-6" />
                <p className="req-field-label mt-6">Performed by</p>
                <p className="mt-1 text-[13px] text-ink">{step.actor}</p>
                <p className="mt-5 text-[14px] leading-relaxed text-muted">{step.body}</p>
              </div>

              <ul className="space-y-4">
                {step.detail.map((item) => (
                  <li key={item} className="flex gap-3 text-[14px] leading-relaxed text-muted">
                    <span aria-hidden="true" className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-accent" />
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </section>
      ))}

      {/* Failure behaviour, stated explicitly. */}
      <section className="border-t border-hairline bg-paper-raised">
        <div className="section py-20">
          <SectionHead
            eyebrow="Edge behaviour"
            title="The cases that are usually left out."
            lede="Each of these is a deliberate decision rather than an accident, and each one is covered by an automated test."
          />
          <div className="mt-12">
            <DisclosureList
              items={[
                {
                  q: "The upload fails after the filing exists. What does the user see?",
                  a: "The filing reference, so the work is not lost. The filing stays in the queue as pending rather than disappearing, because a submission that silently vanishes is worse than one that visibly needs attention.",
                },
                {
                  q: "A file is missing a required column. Is it stored anyway?",
                  a: "No. It is refused at intake and the missing columns are named. Storing a file that cannot support the review would produce a false all-clear later.",
                },
                {
                  q: "Can a filing be reopened after a report is attached?",
                  a: "Yes, and the reopen is itself an audited event. What is not possible is replacing the delivered report in place.",
                },
                {
                  q: "A reviewer makes a mistake and moves a filing to the wrong state.",
                  a: "The transition is refused unless it is a permitted move from the current state, and the permitted moves are documented rather than implied. A move that succeeds is recorded with its actor, so a mistaken move is visible and correctable in the timeline.",
                },
                {
                  q: "The email server is down when a report is delivered. Does the report fail?",
                  a: "No. Delivery is best-effort by design. The report is attached and the status event is written regardless, because an email outage should not block the actual work — and the timeline remains the record of truth if the mail never arrives.",
                },
                {
                  q: "A user is deactivated while they have an open session.",
                  a: "Their sessions end immediately rather than waiting for a cookie to age out. Permission checks also refuse a non-active user regardless of session state.",
                },
              ]}
            />
          </div>
        </div>
      </section>

      <section className="section py-20">
        <SectionHead
          eyebrow="Under the hood"
          title="What each step is actually written as."
          align="center"
        />
        <div className="mx-auto mt-12 max-w-3xl overflow-hidden rounded-card border border-hairline">
          <div className="overflow-x-auto">
            <table className="ruled-table w-full text-left text-[13px]">
              <thead>
                <tr>
                  <th className="px-4 py-3">Step</th>
                  <th className="px-4 py-3">Operation</th>
                  <th className="px-4 py-3">Recorded</th>
                </tr>
              </thead>
              <tbody className="font-mono text-[12px]">
                {[
                  ["Submit", "Presigned upload, then staged-file → filing", "SHA-256, row and column counts, reference"],
                  ["Validate", "Byte-level parse against the filing manifest", "Verdict, reason, row/column counts"],
                  ["Review", "Status transition in a transaction", "Status event: actor, from, to, at"],
                  ["Report", "Attachment of result and source data", "Producer, source, engine version"],
                ].map((row) => (
                  <tr key={row[0]}>
                    <td className="px-4 py-3 font-sans font-medium text-ink">{row[0]}</td>
                    <td className="px-4 py-3 text-muted">{row[1]}</td>
                    <td className="px-4 py-3 text-muted">{row[2]}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
        <p className="mx-auto mt-6 max-w-2xl text-center text-[13px] leading-relaxed text-muted">
          The full request contract — headers, bodies, status codes and error shapes — is in{" "}
          <Link href="/docs#api" className="text-accent underline underline-offset-2">
            the documentation
          </Link>
          .
        </p>
      </section>

      <CtaBand
        title="Run it once end to end."
        body="Create an association, submit a file, move it to review, attach a report. Four steps, and you will have seen every state the timeline can hold."
        primary={{ href: "/signup", label: "Create an association" }}
        secondary={{ href: "/docs", label: "Read the docs" }}
      />
    </>
  );
}
