/**
 * Marketing copy and reference content for the public site.
 *
 * Kept out of the page files so the same facts can be rendered in more than one
 * place (a feature on the landing page and a row in the comparison table) without
 * drifting apart.
 *
 * Everything here describes what the software actually does. Where a control is
 * not implemented, it is listed as not implemented rather than implied — see the
 * compliance and security pages, which are explicit about the gaps because a
 * pre-launch vendor that overstates its posture is worse than one that doesn't.
 */

export type IconName =
  | "upload"
  | "scan"
  | "chain"
  | "report"
  | "shield"
  | "users"
  | "bell"
  | "search";

export interface Feature {
  slug: string;
  title: string;
  icon: IconName;
  summary: string;
  points: string[];
}

export const FEATURES: Feature[] = [
  {
    slug: "ingestion",
    title: "File ingestion",
    icon: "upload",
    summary:
      "CSV and XLSX from a pharmacy system, inspected against the stored bytes rather than the filename.",
    points: [
      "CSV files are parsed for real: row count, column count and detected columns come from the actual header row, with a proper RFC 4180 splitter that handles quoted fields and escaped quotes.",
      "The filing manifest requires two columns to be present in the header — NDC code and Batch number. A file missing either is refused, and the missing names are returned.",
      "Workbooks are checked as ZIP containers, so an .xlsx that is not actually an Excel file is rejected rather than stored.",
      "SHA-256 is computed over the stored bytes, with size limits, extension limits and path-traversal guards on every key.",
      "Files are staged unattached and only bound to a filing on completion, so an interrupted transfer cannot leave a half-created filing behind.",
    ],
  },
  {
    slug: "anomaly-detection",
    title: "Validation intake",
    icon: "scan",
    summary:
      "Each file comes back as valid, warning or invalid — with the reason in words, derived from the bytes.",
    points: [
      "Three verdicts, each carrying a sentence a person can act on rather than a boolean.",
      "Ragged rows are the common real-world defect, so they produce a warning naming how many rows were padded or truncated on intake, instead of a hard rejection.",
      "Findings are stored against the filing rather than recomputed on each page load, so the reviewer sees the same result every time they open it.",
      "Per-cell content analysis — date ranges, quantity types, NDC format — is not yet implemented. Workbook sheet contents are not parsed at intake either; an XLSX is validated as a container and left for on-demand parsing. Both are tracked on the compliance page.",
    ],
  },
  {
    slug: "chain-of-custody",
    title: "Chain of custody",
    icon: "chain",
    summary:
      "Every state change is written server-side, inside the same transaction as the change itself, and can be read back.",
    points: [
      "Server-written status events with the acting user, the previous state and the new state.",
      "The audit event is part of the transaction: a transition that fails leaves no gap in the history.",
      "Filings carry a stable reference such as AP-2026-0001, generated by a database sequence rather than in the browser.",
      "The timeline is the same history an auditor is shown — there is no second, tidier version kept for display.",
    ],
  },
  {
    slug: "reporting",
    title: "Reporting",
    icon: "report",
    summary:
      "A review ends in a report that is attached to the filing, immutable, and exportable.",
    points: [
      "Reports are attached by a super admin and record who produced them.",
      "Structured results and the source document are stored separately, so the panel can render nested results without re-parsing.",
      "A delivered report is never silently replaced. Correcting one means reopening the filing, which is itself audited.",
      "Raw source documents are served through an authorised endpoint, never a public URL.",
    ],
  },
  {
    slug: "tenancy",
    title: "Tenant isolation",
    icon: "shield",
    summary:
      "Associations and pharmacies are separate customers in one deployment, and the separation is enforced by the server.",
    points: [
      "Tenant scope is derived from the session on every request; no route accepts a scope from the client.",
      "Users, filings, files and reports are all filtered by the caller's association or pharmacy.",
      "A member of one pharmacy probing another pharmacy's filing id receives a refusal, not an empty page.",
      "Permissions live in one module with a written specification, rather than role comparisons scattered across routes.",
    ],
  },
  {
    slug: "roles",
    title: "Roles and access",
    icon: "users",
    summary:
      "Four roles, each with a documented boundary, and invite-only account creation.",
    points: [
      "Super admin sees every association; moderators see everything read-only; association admins see their own; workers see only their pharmacy.",
      "Attachments and report production are super-admin actions.",
      "Accounts cannot self-register: an administrator issues a single-use invitation.",
      "Deactivating a user ends their sessions immediately rather than waiting for a cookie to age out.",
    ],
  },
  {
    slug: "notifications",
    title: "Notifications",
    icon: "bell",
    summary: "The events worth an email are sent; the rest stay in the timeline.",
    points: [
      "Invitations, status changes and report delivery are emailed.",
      "Delivery is best-effort by design — a mail outage never fails the action that triggered it.",
      "The timeline remains the record of truth, so a bounced email cannot lose an audit event.",
    ],
  },
  {
    slug: "retrieval",
    title: "Retrieval",
    icon: "search",
    summary: "Find a filing by reference, pharmacy, status or date without opening every row.",
    points: [
      "Filter by status, pharmacy and date range from the filing list.",
      "References are unique and sequential, so a filing can be cited unambiguously in correspondence.",
      "The dashboard's aggregates are computed from the same scoped rows the user can see, so the numbers cannot describe a tenant the user cannot open.",
    ],
  },
];

export interface Solution {
  slug: string;
  audience: string;
  headline: string;
  body: string;
  outcomes: string[];
}

export const SOLUTIONS: Solution[] = [
  {
    slug: "pharmacies",
    audience: "Pharmacies",
    headline: "Send dispensing records once, with proof they arrived.",
    body: "A pharmacy's problem is rarely the review itself — it is the handover. Records get exported from one system, emailed as an attachment, and then nobody can say what was sent or whether it arrived intact. SiroQ replaces that with a filing that has a reference, a checksum per file, and a visible status.",
    outcomes: [
      "A receipt the pharmacy can quote: the filing reference and its current state.",
      "Per-file SHA-256, so a disputed record can be checked against what was actually received.",
      "Rejection states carry a reason, so a returned filing is actionable rather than a formality.",
      "No credentials to share over email — access is granted by invitation, per person.",
    ],
  },
  {
    slug: "associations",
    audience: "Care associations",
    headline: "Run the review queue across every pharmacy you own.",
    body: "An association coordinating submissions across member pharmacies needs one queue, not one spreadsheet per pharmacy. SiroQ scopes every pharmacy to its association, so an administrator sees the whole portfolio while a worker at a member pharmacy sees only their own records.",
    outcomes: [
      "One queue across all member pharmacies, with tenant-scoped results.",
      "Administrator-managed users and invitations across the association.",
      "Per-pharmacy workload and time-to-report visible from the dashboard.",
      "No cross-association visibility, enforced server-side on every request.",
    ],
  },
  {
    slug: "compliance",
    audience: "Compliance officers",
    headline: "Answer 'show me who changed this' without a week of archaeology.",
    body: "The audit question is usually not about the data — it is about the handling. Who received this filing, who moved it to review, who produced the report, and when. Those answers are written server-side as they happen, in the same transaction as the change.",
    outcomes: [
      "An append-only status history per filing, written by the server.",
      "Actor, previous state, new state and timestamp on every transition.",
      "A delivered report that cannot be quietly overwritten.",
      "Documented role boundaries and a written authorization specification.",
    ],
  },
  {
    slug: "auditors",
    audience: "Auditors and regulators",
    headline: "Read the trail rather than reconstruct it.",
    body: "An auditor should not have to reconcile email threads against spreadsheets. The timeline a reviewer sees is the same append-only history the platform stores, and the attached document is the document that was actually received, served through an authorised endpoint.",
    outcomes: [
      "Filing references that are unique, sequential and unambiguous in correspondence.",
      "The stored source document, retrievable per filing.",
      "Role and scope boundaries documented in a specification, not folklore.",
      "Infrastructure and subprocessor list published, so the data path is inspectable.",
    ],
  },
];

export interface Plan {
  name: string;
  price: string;
  cadence: string;
  blurb: string;
  features: string[];
  cta: { href: string; label: string };
  recommended?: boolean;
}

export const PLANS: Plan[] = [
  {
    name: "Starter",
    price: "$0",
    cadence: "per association / month",
    blurb: "One association, a handful of pharmacies, and the full lifecycle.",
    features: [
      "1 association, up to 3 pharmacies",
      "Filing intake and upload",
      "Status timeline and file ledger",
      "Role-based access across 4 roles",
      "Email support",
    ],
    cta: { href: "/signup", label: "Create an association" },
  },
  {
    name: "Professional",
    price: "$240",
    cadence: "per association / month",
    blurb: "For associations running regular review cycles across a portfolio.",
    features: [
      "Unlimited pharmacies",
      "User and invitation management",
      "Report attachment and raw document export",
      "Full chain-of-custody history",
      "Dashboard aggregates and filtering",
      "Priority support",
    ],
    cta: { href: "/contact", label: "Start a trial" },
    recommended: true,
  },
  {
    name: "Enterprise",
    price: "Custom",
    cadence: "annual agreement",
    blurb: "For networks that need operator governance and procurement paperwork.",
    features: [
      "Everything in Professional",
      "Multi-association super admin",
      "Audit trail export",
      "Data residency options",
      "Custom retention and DPA terms",
      "Named contact and review cadence",
    ],
    cta: { href: "/contact", label: "Contact us" },
  },
];

export interface ComparisonRow {
  label: string;
  values: (string | boolean)[];
}

export const COMPARISON: ComparisonRow[] = [
  { label: "Associations", values: ["1", "1", "Unlimited"] },
  { label: "Pharmacies per association", values: ["Up to 3", "Unlimited", "Unlimited"] },
  { label: "Filing intake and upload", values: [true, true, true] },
  { label: "CSV parse + manifest check", values: [true, true, true] },
  { label: "Per-cell content analysis", values: [false, false, "Planned"] },
  { label: "Chain-of-custody history", values: [true, true, true] },
  { label: "Role-based access (4 roles)", values: [true, true, true] },
  { label: "User and invitation management", values: [false, true, true] },
  { label: "Report attachment", values: [false, true, true] },
  { label: "Raw document export", values: [false, true, true] },
  { label: "Dashboard aggregates", values: ["Basic", "Full", "Full"] },
  { label: "Audit trail export", values: [false, false, true] },
  { label: "Data residency options", values: [false, false, true] },
  { label: "Custom DPA and retention", values: [false, false, true] },
  { label: "Support", values: ["Email", "Priority", "Named contact"] },
];

export interface Post {
  slug: string;
  title: string;
  category: "Compliance" | "Regulation" | "Product" | "Case study";
  date: string;
  readingTime: string;
  excerpt: string;
  body: { heading?: string; paragraphs: string[]; list?: string[] }[];
}

export const POSTS: Post[] = [
  {
    slug: "what-a-defensible-audit-trail-contains",
    title: "What a defensible audit trail actually has to contain",
    category: "Compliance",
    date: "2026-08-14",
    readingTime: "6 min",
    excerpt:
      "Most trails fail on the same detail: they record that something changed without recording who, or they are written by the same request that could have failed.",
    body: [
      {
        paragraphs: [
          "An audit trail is usually described as a list of events. That undersells it. The value of the trail is not that it exists — logs exist everywhere — but that it can answer a specific question about a specific record without anyone reconstructing anything.",
          "For a dispensing record, the questions are narrow: who submitted this, who moved it into review, who produced the report, and what did each of them see at the time.",
        ],
      },
      {
        heading: "Four properties, and why each one matters",
        paragraphs: [
          "The first property is attribution. An event with no actor is a rumour. If the writer of the event is not the session that performed the action, the trail is reconstructing history rather than recording it.",
        ],
        list: [
          "Attribution — the event names the user whose session caused it.",
          "Ordering — the timeline is the sequence, not a sort applied at read time.",
          "Completeness — a state change and its event are written together, or neither is.",
          "Immutability — a recorded transition is not edited after the fact.",
        ],
      },
      {
        heading: "The failure that matters: events written after the fact",
        paragraphs: [
          "The subtle failure mode is a two-step write: update the record, then append the event. If the process dies between the two, the record moved and the trail does not say so. Nothing alerts on it, because from the application's point of view the request succeeded.",
          "Writing both in one transaction removes the gap. That is the whole argument, and it is why the implementation detail is worth raising in a procurement conversation rather than accepting a screenshot of a logs page.",
        ],
      },
      {
        heading: "What this means for a reviewer",
        paragraphs: [
          "A reviewer should be able to open a filing and see the same history an auditor would be shown later. If the interface offers a tidier summary than the stored record, the two will diverge, and the tidier one is the one that will be quoted back at you in a dispute.",
        ],
      },
    ],
  },
  {
    slug: "what-a-file-check-actually-proves",
    title: "What an intake check actually proves — and what it does not",
    category: "Product",
    date: "2026-07-02",
    readingTime: "5 min",
    excerpt:
      "A file can be structurally perfect and still be wrong. Here is precisely what SiroQ checks when a CSV arrives, and where the boundary sits.",
    body: [
      {
        paragraphs: [
          "There is a particular kind of vendor claim to avoid: that the system “validates your data”. It sounds reassuring and means almost nothing, because validation can refer to anything from confirming a file is not empty to proving every cell is plausible.",
          "So here is the exact boundary, because it is more useful than the vague version.",
        ],
      },
      {
        heading: "What is checked, from the stored bytes",
        paragraphs: [
          "The check runs server-side against the bytes that were actually stored, not against the filename and not against anything the browser reported. A CSV is decoded with a proper RFC 4180 splitter, so quoted fields and escaped quotes are handled rather than counted as extra columns.",
        ],
        list: [
          "Row count and column count, taken from the file itself.",
          "Detected columns, from the header row.",
          "The filing manifest: NDC code and Batch number must both be present, matched case-insensitively. A file missing either is refused and the missing names come back in the error.",
          "Ragged rows. These are the common real-world defect, so they produce a warning naming how many rows did not match the header width, rather than rejecting the file.",
          "Workbook containers. An .xlsx is checked as a ZIP container, so a renamed CSV is caught instead of being stored.",
        ],
      },
      {
        heading: "What is not checked",
        paragraphs: [
          "Per-cell content analysis does not exist yet. SiroQ does not currently test whether a dispense date falls in the reporting window, whether a quantity is a positive number, or whether an NDC code is well formed. Workbook sheet contents are not parsed at intake either — an XLSX is validated as a container and left for on-demand parsing.",
          "That is a real limit, and it changes what a green verdict means. A file reported as valid has passed a structural and manifest check. It has not been shown to contain clinically sensible dispensing data, and anyone reading a report should not infer that it has.",
        ],
      },
      {
        heading: "Why the warning tier exists",
        paragraphs: [
          "The three verdicts are valid, warning and invalid, and the middle one is doing real work. A file with 12 ragged rows out of 4,000 is overwhelmingly likely to be a genuine export artefact rather than an attack on your data, and rejecting it would teach people to bypass the tool.",
          "Reporting it as a warning — with the count named — keeps the information visible and the submission moving. The alternative, quietly padding the rows, is what the warning exists to prevent.",
        ],
      },
    ],
  },
  {
    slug: "moving-from-shared-drives-to-a-review-queue",
    title: "Moving a review process off a shared drive",
    category: "Regulation",
    date: "2026-05-21",
    readingTime: "7 min",
    excerpt:
      "Shared drives are where audit trails go to be reconstructed from. Here is what usually has to be built before the first filing can be submitted.",
    body: [
      {
        paragraphs: [
          "Most dispensing review processes start in a shared drive: a folder per month, files dropped in by whoever finished the export, and a spreadsheet tracking what arrived. It works until it is audited, and then the effort of reconstructing the trail exceeds the effort of the review itself.",
          "The migration is less about the software than about the decisions. Three of them tend to dominate.",
        ],
      },
      {
        heading: "Decide what a filing is before deciding what a folder is",
        paragraphs: [
          "A filing is one submission for one pharmacy over one period, carrying one or more files. Modelling it as a folder per file means the review unit is the file, and you lose the ability to say that three files arrived together and were assessed as one submission.",
        ],
      },
      {
        heading: "Decide who is allowed to move a filing",
        paragraphs: [
          "In a shared drive, moving a file is a filesystem permission question. In a review queue, moving a filing is a decision with an owner. Separating the roles — the pharmacy submits, an administrator reviews, a super admin reports — is what turns a pile of documents into a process with accountability.",
        ],
      },
      {
        heading: "Decide what happens to a rejected submission",
        paragraphs: [
          "Rejection is where shared drives fail hardest, because a file that was quietly moved out of the folder leaves no trace. A rejected filing should stay visible, keep its history, and carry the reason it was returned. The pharmacy needs to be able to fix and resubmit; the reviewer needs to be able to see that they did.",
        ],
      },
    ],
  },
];

/** Published per role so the docs, the solutions page and the gate agree. */
export const ROLE_MATRIX: {
  role: string;
  audience: string;
  can: string[];
  cannot: string[];
}[] = [
  {
    role: "Super admin",
    audience: "Operator, across every association",
    can: [
      "Every action in the system, across all associations",
      "See every association, pharmacy and filing in the deployment",
      "Attach a report to a filing and produce a delivered result",
      "Manage associations, pharmacies and users",
      "Read raw source documents",
    ],
    cannot: [
      "Rewrite a status event after it is recorded",
      "Replace a delivered report — the filing must be reopened first",
      "Bypass the per-request tenant check, because there is no route that accepts a scope from the client",
    ],
  },
  {
    role: "Moderator",
    audience: "Read-only reviewer across the deployment",
    can: [
      "See every association, pharmacy and filing, for review purposes",
      "Read the filing timeline, findings and attached reports",
    ],
    cannot: [
      "Change anything — creation, status transitions, reports, user management",
      "Read raw source documents",
      "See anything a super admin cannot: this role is a strictly narrower view",
    ],
  },
  {
    role: "Association admin",
    audience: "One association and its member pharmacies",
    can: [
      "See every filing belonging to their association",
      "Invite, update and deactivate users in their association",
      "Create filings on behalf of any pharmacy inside their association",
      "Move filings through the review lifecycle",
      "Read reports attached to their association's filings",
    ],
    cannot: [
      "See another association's data",
      "Attach a report — that is a super-admin action",
      "Read raw source documents",
    ],
  },
  {
    role: "Pharmacy worker",
    audience: "One pharmacy",
    can: [
      "See and create filings for their own pharmacy",
      "Upload dispensing files against those filings",
      "Follow the status timeline of their own filings",
    ],
    cannot: [
      "See any other pharmacy's filings, including sibling pharmacies in the same association",
      "Change a filing's status",
      "Invite users or read reports",
    ],
  },
];

export const FAQ: { q: string; a: string }[] = [
  {
    q: "What file formats do you accept?",
    a: "CSV and XLSX. A CSV must carry NDC code and Batch number in its header row, or it is refused with the missing columns named. CSV row and column counts come from parsing the actual file; an XLSX is validated as a workbook container at intake and its sheet contents are parsed on demand. Size and extension limits are enforced server-side.",
  },
  {
    q: "Does SiroQ check the contents of my dispensing data?",
    a: "At intake it checks the file against the filing manifest — required columns present, columns and rows counted, workbook container valid — and it warns when rows are ragged. It does not yet inspect individual cell values for date ranges, quantity types or NDC format. That analysis is not built, and the compliance page lists it as missing rather than implying otherwise.",
  },
  {
    q: "Who can create an account?",
    a: "Nobody can self-register. An administrator issues a single-use invitation, and the account is created when the invitation is accepted. There is no public signup path that creates an account without an invite.",
  },
  {
    q: "Can a pharmacy see another pharmacy's filings?",
    a: "No. A worker sees only their own pharmacy, and that boundary is applied on every request from the session rather than from anything the client sends. Probing another pharmacy's filing id returns a refusal, not an empty page.",
  },
  {
    q: "What happens if an upload fails halfway through?",
    a: "The bytes are stored before the filing is created, so a failed transfer leaves no filing behind. If the failure happens after the filing exists, the reference is shown on screen and the partial filing stays visible rather than being hidden.",
  },
  {
    q: "Who can attach a report?",
    a: "A super admin only. Reports are the delivered result of a review, so producing one is deliberately separated from moving a filing into review.",
  },
  {
    q: "Can a delivered report be edited?",
    a: "No. Re-attaching is refused. Correcting a report means reopening the filing, which records a new audit event — a delivered document is not quietly replaced.",
  },
  {
    q: "Where is our data stored, and who else touches it?",
    a: "The database and file storage are hosted providers listed on the subprocessors page, and the analysis service is optional and off unless configured. That page is the authoritative list.",
  },
  {
    q: "Are you SOC 2 or HIPAA certified?",
    a: "Not yet, and we would rather say so plainly. The compliance page lists what is in place today, what is in progress, and what is not built — including the controls we know are missing.",
  },
  {
    q: "How do we get our existing filings in?",
    a: "By invitation, then by upload. There is no bulk importer yet; for an initial load we work through it with you during onboarding.",
  },
  {
    q: "Can we host it ourselves?",
    a: "Not currently as a supported option. It runs on ordinary Node and PostgreSQL, so a private deployment is technically straightforward, but we do not ship or support one yet.",
  },
];
